apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: registration-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registration-service/registration-service-cm.yaml") . | sha256sum }}
      labels:
        app: registration-service
        deploymentconfig: registration-service
    spec:
      containers:
      - image: quay.io/qiotproject/all-registration
        imagePullPolicy: Always
        name: registration-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: registration-service
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: registration-service
      volumes:
      - configMap:
          defaultMode: 420
          name: registration-service
        name: registration-service